// src/components/common/loading/loading.vue
<template>
    <div class="loading-wrapper">
        <div class="center-box">
           <div class="rotate">
                <div class="item"></div>
                <div class="item"></div>
                <div class="item"></div>
                <div class="item"></div>
                <div class="item"></div>
                <div class="item"></div>
                <div class="item"></div>
                <div class="item"></div>
            </div> 
        </div>
    </div>
</template>
<style lang="scss" src="./index.scss"></style>

// src/components/common/loading/index.tsx
import * as React from "react";
import { 
    render,
    unmountComponentAtNode
 } from "react-dom";
import "./index.scss";

export default function Loading () {
    return (
        <div className="loading-wrapper">
           <div className="loading-rotate"></div> 
        </div>
    );
}

let div = document.createElement("div");

const loading = {
    show() {
        if (!div.parentNode) {
            document.body.appendChild(div);
        }
        render(<Loading/>, div);
    },
    hide() {
        unmountComponentAtNode(div);
    }
};

export {
    loading
}
