// src/components/admin/modify-pwd/index.tsx
import * as React from "react";
import {
    Dialog,
    DialogActions,
    DialogContent,
    DialogTitle,
    TextField,
    Button
} from "@material-ui/core";
import message from "@common/message";
import _fetch from "@common/fetch";
import { MODIFY_PASSWORD } from "@common/api";
import md5 from "blueimp-md5";
import "./index.scss";

interface Props {
    visible?: boolean;
    hideDialog?: () => void;
}

export default class ModifyPwd extends React.Component<Props> {
    state = {
        origPwd: "",
        newPwd: "",
        rePwd: "",
        disabled: false
    }

    origPwdRef: React.RefObject<HTMLInputElement> = React.createRef();
    newPwdRef: React.RefObject<HTMLInputElement> = React.createRef();
    rePwdRef: React.RefObject<HTMLInputElement> = React.createRef();

    close = () => {
        this.setState({
            origPwd: "",
            newPwd: "",
            rePwd: ""
        });
        this.props.hideDialog();
    }

    handleChange = (type: string, evt: React.ChangeEvent<HTMLInputElement>) => {
        this.setState({
            [type]: evt.target.value
        });
    }

    save = async () => {
        let {
            origPwd,
            newPwd,
            rePwd
        } = this.state;
        let {
            origPwdRef,
            newPwdRef,
            rePwdRef
        } = this;
        if (!origPwd) {
            origPwdRef.current.focus();
        } else if (!newPwd) {
            newPwdRef.current.focus();
        } else if (!rePwd) {
            rePwdRef.current.focus();
        }
        if (newPwd !== rePwd) {
            return message.error("新密码和重复密码输入不一致");
        }
        this.setState({
            disabled: true
        });
        try {
            await _fetch(MODIFY_PASSWORD, {
                method: "post",
                body: {
                    origPwd: md5(origPwd),
                    newPwd: md5(newPwd)
                }
            });
            this.props.hideDialog();
            message.success("修改成功");
        } catch (error) { }
        this.setState({
            disabled: false
        });
    }

    render() {
        let {
            origPwd,
            newPwd,
            rePwd,
            disabled
        } = this.state;
        return (
            <Dialog open={this.props.visible} className="modify-pwd-dialog">
                <DialogTitle>修改密码</DialogTitle>
                <DialogContent>
                    <div className="pwd-row">
                        <TextField
                            inputRef={this.origPwdRef}
                            type="password"
                            placeholder="原密码"
                            onChange={evt => this.handleChange("origPwd", evt as any)}
                            value={origPwd} />
                    </div>
                    <div className="pwd-row">
                        <TextField
                            inputRef={this.newPwdRef}
                            type="password"
                            placeholder="新密码"
                            onChange={evt => this.handleChange("newPwd", evt as any)}
                            value={newPwd} />
                    </div>
                    <div className="pwd-row">
                        <TextField
                            inputRef={this.rePwdRef}
                            type="password"
                            placeholder="重复密码"
                            onChange={evt => this.handleChange("rePwd", evt as any)}
                            value={rePwd} />
                    </div>
                </DialogContent>
                <DialogActions>
                    <Button onClick={this.save} disabled={disabled} color="primary">
                        确定
                    </Button>
                    <Button onClick={this.close}>
                        取消
                    </Button>
                </DialogActions>
            </Dialog>
        );
    };
}

// src/components/common/modifyPwd/index.vue
<template>
    <div class="modify-pwd-wrapper">
        <div class="form-flex">
            <span class="form-label">原密码</span>
            <input type="password" class="v-input form-control" v-model="oldPwd">
        </div>
        <div class="form-flex">
            <span class="form-label">新密码</span>
            <input type="password" class="v-input form-control" v-model="newPwd">
        </div>
        <div class="form-flex">
            <span class="form-label">重复密码</span>
            <input type="password" class="v-input form-control" v-model="confirm">
        </div>
        <div class="form-flex">
            <span class="form-label"></span>
            <div class="form-control">
                <v-button type="primary" @click="ok">确定</v-button>
                <v-button style="margin-left: 10px;" @click="cancel">取消</v-button>
            </div>
        </div>
    </div>
</template>

<style lang="scss">
@media screen and (min-width: 641px) {
    .modify-pwd-wrapper {
        width: 300px;
        margin: 0 auto;
        .form-label {
            width: 60px;
            text-align: right;
        }
        .v-input {
            width: 240px;
            flex-grow: 0;
        }
    }
}
</style>

<script>
import VButton from "../../common/button";
import fetch from "../../common/fetch";
import message from "../../common/message/index";
import { MODIFY_PASSWORD } from "../../common/api";
import md5 from "blueimp-md5";

export default {
    components: {
        VButton
    },
    data() {
        return {
            oldPwd: "",
            newPwd: "",
            confirm: ""
        };
    },
    methods: {
        async ok() {
            let { oldPwd, newPwd, confirm } = this;
            if (!oldPwd || !newPwd || !confirm) return;
            if (newPwd !== confirm) {
                message.error("新密码和重复密码不一致!");
                return;
            }
            try {
                await fetch(MODIFY_PASSWORD, {
                    method: "post",
                    body: {
                        newPwd: md5(newPwd),
                        oldPwd: md5(oldPwd)
                    }
                });
                message.success("修改成功!");
            } catch(err){}
        },
        cancel() {
            this.$router.go(-1);
        }
    }
};
</script>
